MySQL:
  url: localhost
  port: 3306
  user: root
  password: ''
  database: test
  table: globalprefix

Settings:
  ConsoleUpdateFeedback: true
  WareHouse:
    toggle-prefix: '&7查看后缀'
    toggle-suffix: '&7查看前缀'
    next: '&7下一页'
    back: '&7上一页'
    useing: ' &a[使用中]'
    item:
      type: PAPER
      data: 0
      name: '<name>'
      lore:
      - ''
      - '&8&o点击切换为该称号'
    empty:
      type: WOOL
      data: 14
      name: '&4空'
      lore:
      - ''
      - '&8&o尚未获得任何称号'

Messages:
  loaded: '&6&lGlobalPrefix &8> &a插件已载入'
  placeholder:
    notfound: '&6&lGlobalPrefix &8> &7尚未发现 PlaceholderAPI 插件!'
    hook: '&6&lGlobalPrefix &8> &2已注册 PlaceholderAPI 变量!'
    empty: '-'
  command:
    query:
    - '&6命令帮助'
    - '&a/gp query &4查看自己的称号情况'
    - '&a/gp warehouse &4查看自己的称号仓库'
    update:
    - '&a/gp update &7[player] [p|s] [text] &4设置称号'
    add:
    - '&a/gp add &7[player] [p|s] [text] &4添加称号到仓库'
    del:
    - '&a/gp del &7[player] [p|s] [text] &4从仓库移除称号'
  query:
    notfound: '&6&lGlobalPrefix &8> &7你没有称号哦'
    found:
    - '&6我的称号'
    - '&a前缀: &f<prefix>'
    - '&a后缀: &f<suffix>'
  update:
    empty: '&6&lGlobalPrefix &8> &4参数不全'
    success:
    - '&6称号已更新'
    - '&a前缀: &f<prefix>'
    - '&a后缀: &f<suffix>'
  add:
    empty: '&6&lGlobalPrefix &8> &4参数不全'
    success: '&6&lGlobalPrefix &8> &7成功为玩家 &f<player>&7 添加称号&f <variable>'
  del:
    empty: '&6&lGlobalPrefix &8> &4参数不全'
    success: '&6&lGlobalPrefix &8> &7成功移除玩家 &f<player>&7 的称号&f <variable>'
  warehouse:
    title-prefix: '称号仓库 - 前缀'
    title-suffix: '称号仓库 - 后缀'
    messages:
      loading: '&7正在加载称号仓库...'
      loaded: '&7载入成功!'
      already: '&c你正在使用这个称号哦'
      success: '&2称号已更换为: §f<variable>'
  connection:
    close: '&6&lGlobalPrefix &8> &4数据库连接已关闭, 请检查!'